export const STORE_TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  CLEAR_CART: "CLEAR_CART",
  START_PURCHASE: "START_PURCHASE",
  PURCHASE_SUCCESS: "PURCHASE_SUCCESS",
  PURCHASE_ERROR: "PURCHASE_ERROR",
};
